logging.level.org.springframework.security=DEBUG

spring.application.name=auth-service
server.port=8080
eureka.client.service-url.defaultZone=http://eureka-server:12312/eureka

# data
spring.datasource.url=jdbc:postgresql://postgres:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# security
security.token-validity-duration=86400
security.session-cookie-name=JSESSIONID
security.login-url=/login
security.login-page=/WEB-INF/jsp/auth/login.jsp
security.register-url=/register
security.register-page=/WEB-INF/jsp/auth/register.jsp

# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m

# redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=1234
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
# redis session management
spring.session.timeout=600

spring.jackson.deserialization.fail-on-unknown-properties=false