#logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.data.redis.serializer=DEBUG


spring.application.name=auth-service
server.port=0
eureka.client.service-url.defaultZone=http://localhost:12312/eureka

# data
spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# security
security.token-validity-duration=86400
security.session-cookie-name=JSESSIONID
security.login-url=/login
security.login-page=/WEB-INF/jsp/auth/login.jsp
security.register-url=/register
security.register-page=/WEB-INF/jsp/auth/register.jsp

# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=1234
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
# redis session management
spring.session.timeout=600

spring.jackson.deserialization.fail-on-unknown-properties=false