name: gjj-web

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379
    volumes:
      - /c:/redis:/root/redis
      - /c:/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=1234

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_PASSWORD=21122012loliwe+
      - POSTGRES_USER=postgres
    volumes:
      #- ./db/dumps/social_network_dump.sql:/docker-entrypoint-initdb.d/social_network_dump.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d social_network" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672
      - 5672

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/social_network"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATA_REDIS_HOST: "redis"

volumes:
  postgres_data: