<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.getjavajob</groupId>
        <artifactId>web-social-network</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dao</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.getjavajob</groupId>
            <artifactId>common</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <db.url>jdbc:postgresql://localhost:5432/social_network</db.url>
                <db.login>postgres</db.login>
                <db.password>21122012loliwe+</db.password>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <db.url>jdbc:postgresql://178.250.246.184:5432/social_network</db.url>
                <db.login>socialnetwork</db.login>
                <db.password>21122012war</db.password>
            </properties>
        </profile>
    </profiles>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>