spring.application.name=friendship-service
server.port=8084
eureka.client.service-url.defaultZone=http://localhost:12312/eureka
eureka.instance.prefer-ip-address=false
# redirects
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.host-header=x-forwarded-host
# data
spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=1234
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
# redis session management
spring.session.timeout=600
spring.jackson.deserialization.fail-on-unknown-properties=false
