spring.application.name=message-service
server.port=8080
eureka.client.service-url.defaultZone=http://eureka-server:12312/eureka
# processing forward headers
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.host-header=x-forwarded-host
# websockets
websocket.message-size-limit=204800
websocket.send-buffer-size-limit=524288
websocket.send-time-limit=10000
# data
spring.datasource.url=jdbc:postgresql://postgres:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# redis caching
redis.cache.newsfeed.size=10
redis.cache.newsfeed.key.prefix=feed:
# redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
# redis session management
spring.session.timeout=600