spring.application.name=message-service
server.port=8086
eureka.client.service-url.defaultZone=http://localhost:12312/eureka
# data
spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m
# redis caching
redis.cache.newsfeed.size=10
redis.cache.newsfeed.key.prefix=feed:
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
# redis session management
spring.session.timeout=600