spring.application.name=ui-service
server.port=0
eureka.client.service-url.defaultZone=http://localhost:12312/eureka

# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m