spring.application.name=ui-service
server.port=8080
eureka.client.service-url.defaultZone=http://eureka-server:12312/eureka
# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m