# General Settings
spring.application.name=discovery-server
server.port=12312
# Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka
# Instance Settings
eureka.instance.prefer-ip-address=false