# server
server.port=8081

# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m

# websockets
websocket.message-size-limit=204800
websocket.send-buffer-size-limit=524288
websocket.send-time-limit=10000

# data
spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# security
security.token-validity-duration=86400
security.session-cookie-name=JSESSIONID
security.login-url=/login
security.login-page=/WEB-INF/jsp/auth/login.jsp
security.register-url=/register
security.register-page=/WEB-INF/jsp/auth/register.jsp

# rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest