# server
server.port=8081
# web
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.session.timeout=10m
# data
spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=21122012loliwe+
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect